import Banner from '@/Components/Banner'
import Footer from '@/Components/Footer'
import Navbar from '@/Components/Navbar'
import Section1 from '@/Components/Section1'
import Section2 from '@/Components/Section2'
import Section3 from '@/Components/Section3'
import { Heading } from '@chakra-ui/react'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Hiking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Section1 />
      <Section2 />
      <Section3 />
      <Footer />
    </>
  )
}
